name: Build & Publish Docker
on:
  push:
    branches:
      - 'dev/**'

jobs:
  docker-amd64:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Install Python3   
      uses: actions/setup-python@v6
      with:
        python-version: '3.11'
        architecture: 'x64'

    - name: Checkout
      uses: actions/checkout@v5
      with:
        submodules: true
        fetch-depth: 0

    - name: Build Docker Images
      run: python build.py --platform linux-amd64
      env:
        DOCKER_REPO: ${{ secrets.DOCKER_REPO }} 
        DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }} 
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 

  docker-arm64:
    runs-on: ubuntu-24.04-arm
    permissions: write-all

    steps:
    - name: Install Python3   
      uses: actions/setup-python@v6
      with:
        python-version: '3.11'
        architecture: 'arm64'

    - name: Checkout
      uses: actions/checkout@v5
      with:
        submodules: true
        fetch-depth: 0

    - name: Build Docker Images
      run: python build.py --platform linux-arm64
      env:
        DOCKER_REPO: ${{ secrets.DOCKER_REPO }} 
        DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }} 
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 